/**
 * Session Recap Extension
 *
 * After each agent response, injects a subtle footer showing:
 *   ✻ Done in 55s  ※ recap: what was done + what's next  (disable: /config recaps off)
 *
 * Recap text is generated by the cheapest available model (Gemini Flash Lite → active model).
 * Falls back to timing-only if no model is available or the call times out.
 *
 * Settings (registered into the shared /config registry owned by config-center):
 *   /config recaps on|off          Enable/disable recaps (default on)
 *   /config recap-model <id|auto>  Pick the model used to write recaps
 *   /config                        UI for all registered settings
 */

import { complete } from "@earendil-works/pi-ai/compat";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";

// Cheap, authed models tried first; ctx.model is the guaranteed-authed backstop.
const RECAP_MODELS: Array<{ provider: string; id: string }> = [
	{ provider: "google-aistudio", id: "gemini-flash-lite-latest" },
	{ provider: "google-aistudio", id: "gemini-2.5-flash-lite" },
];

const RECAP_TIMEOUT_MS = 10_000;
const MAX_RECAP_TOKENS = 80;

function formatDuration(ms: number): string {
	if (ms < 1000) return "<1s";
	const s = Math.round(ms / 1000);
	if (s < 60) return `${s}s`;
	const m = Math.floor(s / 60);
	const rem = s % 60;
	return rem > 0 ? `${m}m ${rem}s` : `${m}m`;
}

function buildSnippet(messages: any[]): string {
	const lines: string[] = [];
	for (const msg of messages) {
		const role = msg?.role;
		const content = msg?.content;
		if (!role || !content) continue;

		if (role === "user") {
			const text =
				typeof content === "string"
					? content
					: Array.isArray(content)
						? content
								.filter((c: any) => c?.type === "text")
								.map((c: any) => c.text)
								.join("\n")
						: "";
			if (text.trim()) lines.push(`User: ${text.slice(0, 600).trim()}`);
		} else if (role === "assistant") {
			const parts = Array.isArray(content) ? content : [];
			const text = parts
				.filter((c: any) => c?.type === "text")
				.map((c: any) => c.text)
				.join("\n");
			const toolNames = parts.filter((c: any) => c?.type === "toolCall").map((c: any) => String(c.name));
			if (text.trim()) lines.push(`Assistant: ${text.slice(0, 400).trim()}`);
			if (toolNames.length > 0) lines.push(`Tools used: ${toolNames.join(", ")}`);
		}
	}
	return lines.join("\n\n");
}

const RECAP_DELAY_MS = 3 * 60 * 1000; // 3 minutes of inactivity before showing recap

// Models offered for the recap-model setting (auto = existing cheap-first chain).
const MODEL_VALUES = ["auto", ...RECAP_MODELS.map((m) => `${m.provider}/${m.id}`)];

// Inline registry helper — see config-center.ts. globalThis so it works
// regardless of extension load order or bundling; no shared import needed.
function registerSetting(s: {
	id: string;
	label: string;
	values: string[];
	get: () => string;
	set: (v: string) => void;
}) {
	const g = globalThis as any;
	g.__piConfigSettings ??= new Map();
	g.__piConfigSettings.set(s.id, s);
}

export default function (pi: ExtensionAPI) {
	let enabled = true;
	let recapModelOverride = "auto";
	let requestStart = 0;
	let pendingTimer: ReturnType<typeof setTimeout> | null = null;
	let pendingMessages: any[] | null = null;
	let pendingElapsed = 0;

	// Restore toggle preference from session history
	pi.on("session_start", (_event, ctx) => {
		for (const entry of ctx.sessionManager.getEntries()) {
			if (entry.type === "custom" && (entry as any).customType === "recap-config") {
				enabled = (entry as any).data?.enabled ?? true;
				recapModelOverride = (entry as any).data?.model ?? "auto";
			}
		}
	});

	pi.on("agent_start", () => {
		requestStart = Date.now();
		// Cancel any pending recap since the user is active again
		if (pendingTimer) {
			clearTimeout(pendingTimer);
			pendingTimer = null;
			pendingMessages = null;
		}
	});

	pi.on("agent_end", (event, ctx) => {
		if (!enabled) return;
		const elapsed = requestStart > 0 ? Date.now() - requestStart : 0;

		// Cancel any existing pending timer and restart the debounce
		if (pendingTimer) {
			clearTimeout(pendingTimer);
		}

		pendingMessages = event.messages;
		pendingElapsed = elapsed;

		pendingTimer = setTimeout(() => {
			pendingTimer = null;
			const messages = pendingMessages;
			pendingMessages = null;
			if (!messages) return;

			void (async () => {
				try {
					const doneStr = `✻ Done in ${formatDuration(pendingElapsed)}`;
					let recap = "";

					try {
						const snippet = buildSnippet(messages);
						if (snippet.trim()) {
							// Cheap configured models first, then the active model as a
							// guaranteed-authed backstop. De-dupe to avoid retrying one.
							const candidates: any[] = [];
							const seen = new Set<string>();
							const add = (m: any) => {
								if (!m) return;
								const key = `${m.provider}/${m.id}`;
								if (seen.has(key)) return;
								seen.add(key);
								candidates.push(m);
							};
							// User-pinned recap model first (falls through to auto chain if it
							// can't resolve/auth). Split on FIRST slash: ids may contain slashes.
							if (recapModelOverride !== "auto") {
								const slash = recapModelOverride.indexOf("/");
								if (slash > 0)
									add(
										ctx.modelRegistry.find(
											recapModelOverride.slice(0, slash),
											recapModelOverride.slice(slash + 1),
										),
									);
							}
							for (const { provider, id } of RECAP_MODELS) add(ctx.modelRegistry.find(provider, id));
							add(ctx.model);

							for (const model of candidates) {
								try {
									const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
									if (!auth.ok || !auth.apiKey) continue;

									const response = await complete(
										model,
										{
											messages: [
												{
													role: "user",
													content: [
														{
															type: "text",
															text: `Summarize in 1 sentence (max 140 chars, no preamble): what the user asked, what was done, and what's next.\n\n${snippet}`,
														},
													],
													timestamp: Date.now(),
												},
											],
										},
										{
											apiKey: auth.apiKey,
											headers: (auth as any).headers,
											maxTokens: MAX_RECAP_TOKENS,
											signal: AbortSignal.timeout(RECAP_TIMEOUT_MS),
										},
									);

									recap = response.content
										.filter((c): c is { type: "text"; text: string } => c.type === "text")
										.map((c) => c.text)
										.join(" ")
										.trim();

									if (recap) break;
								} catch {
									// Try next model
								}
							}
						}
					} catch {
						// No recap on failure — timing-only fallback below
					}

					const hint = " (disable: /config recaps off)";
					const content = recap ? `${doneStr}  ※ recap: ${recap}${hint}` : doneStr;
					pi.sendMessage({
						customType: "session-recap",
						content,
						display: true,
					});
				} catch {
					// Context went stale (session switch/reload/fork) — silently discard
				}
			})();
		}, RECAP_DELAY_MS);
	});

	// Minimal single-line renderer — subtle, no background box
	pi.registerMessageRenderer("session-recap", (message, _options, theme) => {
		return new Text(theme.fg("dim", String(message.content ?? "")), 0, 0);
	});

	// Register settings into the shared /config registry (config-center owns the
	// command + UI). Persist toggles to session history so they survive reload.
	const persistConfig = () => pi.appendEntry("recap-config", { enabled, model: recapModelOverride });
	registerSetting({
		id: "recaps",
		label: "Session recaps",
		values: ["on", "off"],
		get: () => (enabled ? "on" : "off"),
		set: (v) => {
			enabled = v === "on";
			persistConfig();
		},
	});
	registerSetting({
		id: "recap-model",
		label: "Recap model",
		values: MODEL_VALUES,
		get: () => recapModelOverride,
		set: (v) => {
			recapModelOverride = v;
			persistConfig();
		},
	});
}
